### ISSUE TITLE
Include individual SVGs in NPM Package

### ISSUE THREAD

**Issue by jkusa** [denali-design/denali-icon-font#43]
Including the individual SVGs in the NPM package will allow users to use Denali icons via inline SVG.

Beyond the benefits listed [here](https://github.blog/2016-02-22-delivering-octicons-with-svg/) and [here](https://css-tricks.com/icon-fonts-vs-svg/), this will allow users to pick and choose what icons they want to pull into their bundle instead of pulling in all of them.

**Comment by chasturansky** [comment]
The icon assets are now available in the npm package.

We are coming out with another package that uses SVG symbols in the coming weeks.
