### ISSUE TITLE
Request: Connection Icon

### ISSUE THREAD

**Issue by ope-nz** [denali-design/denali-icon-font#45]
Could I please request an icon to represent a connection (e.g. a database connection). This is usually an icon representing a plug.

![image](https://user-images.githubusercontent.com/26259049/78299427-66e24000-7592-11ea-85e8-72a0d9422586.png)

**Comment by chasturansky** [comment]
We have created this icon. It is available in our latest version 1.4

You can preview the icon [here](https://denali-design.github.io/denali-icon-font/docs/#plug-connect).

I will be closing this request if you need anything else, feel free to create another issue.

**Comment by ope-nz** [comment]
@chasturansky that's amazing! It looks great! Thanks for all your hard work.
