### ISSUE TITLE
Request: Chart Trends

### ISSUE THREAD

**Issue by ope-nz** [denali-design/denali-icon-font#60]
Could I please request some additional icons to indicate chart trends?

So similar to d-chart-upward but one for trending downward and one trending flat/stable/steady (i.e a horizontal line)

Something like this;

![image](https://user-images.githubusercontent.com/26259049/86632365-69d24e00-c023-11ea-88d3-38993e5b8f6c.png)
and
![image](https://user-images.githubusercontent.com/26259049/86632934-20363300-c024-11ea-83ed-9cc49746e803.png)

**Comment by ope-nz** [comment]
Oh sorry, I obviously didnt look hard enough, I see those are already there. Apologies :(

**Comment by chasturansky** [comment]
No worries! Let us know if you need anything else.
