### ISSUE TITLE
Icon request: question mark

### ISSUE THREAD

**Issue by OronNadiv** [denali-design/denali-icon-font#67]

**Comment by chasturansky** [comment]
Hi @OronNadiv, We currently have two question mark icons labeled as help. Do you just want a plain question mark with no container?

<img width="181" alt="Screen Shot 2020-09-29 at 10 27 03 PM" src="https://user-images.githubusercontent.com/15337851/94646409-0c0c7580-02a3-11eb-8199-96fd1fa8ccc8.png">
<img width="211" alt="Screen Shot 2020-09-29 at 10 27 07 PM" src="https://user-images.githubusercontent.com/15337851/94646411-0ca50c00-02a3-11eb-848b-834cd52e52eb.png">

**Comment by OronNadiv** [comment]
Yes, I meant an empty question mark. Not a big deal since those two work as well. Thank you @chasturansky .

**Comment by chasturansky** [comment]
Included in v1.7
