### ISSUE TITLE
Icon Request: hint icon

### ISSUE THREAD

**Issue by shadiabuhilal** [denali-design/denali-icon-font#68]
![hint-icon](https://user-images.githubusercontent.com/1387462/94526994-3c90d880-01eb-11eb-8706-888bf9b5f890.png)

**Comment by chasturansky** [comment]
@shadiabuhilal We currently have an info icon wrapped in a circle, see below. Do you just want the i on its own?

<img width="239" alt="Screen Shot 2020-09-29 at 10 28 40 PM" src="https://user-images.githubusercontent.com/15337851/94646516-3cecaa80-02a3-11eb-84b4-35c08c38588e.png">

**Comment by shadiabuhilal** [comment]
Thanks @chasturansky for your response. 

I didn't think `information-circle` is the right icon for hint.
hint icons should be small and clean, so it looks like a part of the hint text.

**Comment by chasturansky** [comment]
Included in v1.7
