### ISSUE TITLE
Icon Request: Shipping And Delivery icons

### ISSUE THREAD

**Issue by shadiabuhilal** [denali-design/denali-icon-font#89]

**Comment by chasturansky** [comment]
@shadiabuhilal Do you have any reference images for these?

**Comment by shadiabuhilal** [comment]
Please check https://www.google.com/search?q=delivery%20and%20shipping%20icon&tbm=isch&tbs=isz:i&prmd=insv&hl=en&sa=X&ved=0CAMQpwVqFwoTCIjFsfyUie4CFQAAAAAdAAAAABAD&biw=980&bih=1472#imgrc=J0bqKYDUn1vT4M
