### ISSUE TITLE
Icon Request: User Role

### ISSUE THREAD

**Issue by ope-nz** [denali-design/denali-icon-font#90]
Could I please request an icon to represent a "User Role".

Something with the single user icon and a small cog/lock/shield - one of each would be great.

Something like this;

![image](https://user-images.githubusercontent.com/26259049/104383295-787e5c80-5594-11eb-9915-8d1abcc067fa.png)

Thanks and keep up the great work!

**Comment by chasturansky** [comment]
Yes, we can create that set of user icons. We do have a user in a shield you can find that [here](https://denali-design.github.io/denali-icon-font/docs/#user-secure).

We'll label them `user-settings` `user-lock` `user-unlock`

**Comment by ope-nz** [comment]
Thanks that would be great.

I am aware of the "user-secure" icon but am needing something visually similar to the "user-group" icon for my app which reports on users, the groups the belong to and also the role of the user.

![image](https://user-images.githubusercontent.com/26259049/104509241-429dae80-564e-11eb-991d-3a714b59c57a.png)

**Comment by chasturansky** [comment]
These are the icons we created.
<img width="571" alt="Screen Shot 2021-01-13 at 2 24 21 PM" src="https://user-images.githubusercontent.com/15337851/104517563-1715b800-55ab-11eb-8353-e946134d1deb.png">

**Comment by chasturansky** [comment]
Would they work for your situation?

**Comment by ope-nz** [comment]
@chasturansky those are perfect! Thanks so much.

**Comment by chasturansky** [comment]
These will be release in the next version of Denali icons.
