### ISSUE TITLE
Icon Request: Magic/Wand

### ISSUE THREAD

**Issue by ope-nz** [denali-design/denali-icon-font#91]
Hi Team, could I request an icon for a "magic wand"?

Something similar to this;

![image](https://user-images.githubusercontent.com/26259049/105098460-f996a000-5b0e-11eb-8343-0ca43d11b231.png)
or this
![image](https://user-images.githubusercontent.com/26259049/105098582-2480f400-5b0f-11eb-82f8-82d53715d531.png)

Thanks in advance!

**Comment by chasturansky** [comment]
Hi, We'll include this in our next sprint. Again thank you for all the icon recommendations!

**Comment by chasturansky** [comment]
These will be release in the next version of Denali icons.
