### ISSUE TITLE
Discord icon

### ISSUE THREAD

**Issue by NoAccount1** [denali-design/denali-icon-font#92]
Hello, could i request two Discord icons like the following images

![discordicon2](https://user-images.githubusercontent.com/74969657/106482495-c9a3b100-64ad-11eb-97b2-e60f50eeccbd.png)
![discordicon](https://user-images.githubusercontent.com/74969657/106482534-d32d1900-64ad-11eb-846b-15b18f6204ae.png)

Thank you

**Comment by chasturansky** [comment]
Thank you for submitting a request. We'll add this to the next batch.

**Comment by chasturansky** [comment]
These will be release in the next version of Denali icons.
