### ISSUE TITLE
Icon Request: Bulk

### ISSUE THREAD

**Issue by marcosand** [denali-design/denali-icon-font#93]

**Comment by chasturansky** [comment]
@marcosand Can you please provide an example of a bulk icon?

**Comment by marcosand** [comment]
@chasturansky Was previously sharing ideas with @torresr03, but don't think we finalized a direction. Here were a few Ideas I had.

<img width="118" alt="Screen Shot 2021-03-19 at 8 11 45 AM" src="https://user-images.githubusercontent.com/58989034/111802154-ea23a100-888a-11eb-94a2-b8c5b3d5f32f.png">

<img width="121" alt="Screen Shot 2021-03-19 at 8 11 25 AM" src="https://user-images.githubusercontent.com/58989034/111802187-f27bdc00-888a-11eb-988d-05d46e4a1382.png">

<img width="112" alt="Screen Shot 2021-03-19 at 8 13 27 AM" src="https://user-images.githubusercontent.com/58989034/111802245-01fb2500-888b-11eb-9af4-167e925be163.png">
